# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f549487c79ceec8164b2fc738f8280a0eda637b356c28261b9fbacbb5b3b83130436e8a8298ce781977e0ac6664801b11285c19f744ac3122e6d20e531ea0b

test:
  secret_key_base: 0e3cec96577a600d303ec85e4548a0e6efe4b9fbfb9c0ea6ea9dea558aaa58cc396402c7c82b51c828edfaf1261514f206bb5a1d6647190dc5bf5436b6f4aebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
